Разбивка компонента «Конструктор пиццы» на мелкие компоненты
htmlacademy-vue/274677-pizza-1 pull request #2
Opened 2021-07-14 20:36 UTC by bazikk

2021-07-14 21:59 UTC, Djaler requested changes

2021-07-14 21:59 UTC, Djaler commented on src/frontend/src/common/components/AppDrag.vue
> +    :draggable="true"
нужно сделать, чтобы draggable можно было отключать (если количество ингредиентов 3)

2021-07-14 21:59 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +                item.count > 1
по ТЗ это не совсем очевидно, но вот как это должно работать:
если ингредиентов одинаковых несколько, то должно отображаться и несколько дивов для него. у второго будет добавлен класс `pizza__filling--second`, у третьего `pizza__filling_third`.
Это логичнее выглядит с точки зрения отображения - когда увеличивается количество ингредиента, также увеличивается количество отображаемых элементов

2021-07-15 21:24 UTC, bazikk commented on src/frontend/src/common/components/AppDrag.vue
> +    :draggable="true"
Поправил

2021-07-15 21:26 UTC, bazikk commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +                item.count > 1
А я еще думал, что странно как то придумали, что при добавлении ингредиентов они просто поворачиваются на 45 градусов)

Поправил этот момент

2021-07-16 05:23 UTC, merged